apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  database_url: mongodb-service

# store username and password in base64 format
# type 'opaque' is for key-value pair, we have others like TLS
